# TB01 independent review B (tier 1)

Fresh review of frozen TB01 manifest SHA256 `7683d900cb639ee71051144edb1bb39e9c3918cb5a6cb77a421dc2839daed318`. Inspected the current block manifest, claims and witness maps, all three Lean modules, `Audit.lean`, `scripts/verify_traffic_proofs.py` with its shared source scanner, and `docs/traffic-proof-handoff.md`. Re-read the changed Reuse and Ingress source after the model operation rename to `acceptRequest` and the ingress event rename to `charge`. The cited candidate report records two passing clean builds, 560 declarations, and no axioms; its overall status is BLOCKED because candidate mode omits review-ladder validation. This review is advisory and does not claim to have run those builds.

No constructed invariant breach found. In Reuse, `acceptRequest` validates modeled delivery identity before adding a subscriber, then checks the full structural key in cache and queued jobs. Cancellation removes only matching channel/subscriber rows and calls `pruneQueued`; queued work remains with another subscriber, while running work remains in both `jobs` and `running` after its last subscriber detaches. `RunningOwned` is maintained over reachable transitions, so completion/failure removes a running key from both lists together. W03 supplies concrete queued and running cancellation traces. Capability authenticity, runtime atomicity, and production lock/linearization behavior remain outside the model.

Reuse keys are exact structural `DecidableEq` values. `Key` contains full `Context`, kind, and options; context contains raw bytes, environment, ordered pool, policies, bounds, and other identity fields. Canonical and AST structural keys differ, while behavior keys intentionally ignore the selected structural metric. Cache and pin soundness are relative to the supplied mathematical `eval`; W20 and W21 cover metric omission and delivery mismatch. I found no counterexample to those statements. Actual extraction/encoding, collision handling, Java evaluator behavior, and fresh/warm JVM equivalence remain open as documented.

Resources proves reachable bounds for declared charges, simultaneous owner uniqueness, and modeled process incarnation/ticket protocol properties. The generic ledger's delayed stale release after external owner-ID reuse is explicitly represented by `owner_reuse_breach` and excluded from its safety claim; the pool separately issues fresh incarnations. Declared bytes are not measured memory, and reap is an input event rather than proof of OS termination.

Ingress uses natural-number logical ticks. Read progress requires the idle and absolute deadline constraints. Frame acceptance checks expected ticket, valid modeled fields, payload-length agreement, a cap-bounded allocation plan, and `now < deadline`; successful consumption returns the worker phase to idle. Request handling validates parsed header/body values and creates checked allocation plans. The changed `.charge` event debits one modeled token when available; insufficient credit is a no-op. The model does not perform real allocation or decode raw transport bytes. Parser, clock, physical allocation, overflow and composed scheduling correspondence remain outside the claim.

The verifier binds frozen inputs and review artifacts, checks the theorem inventory and transitive axioms from the Lean audit stream, compares two clean builds, and includes negative controls. The current public handoff and manifest state production refinement is false/open and all 23 end-to-end obligations remain OPEN. The claims expressly exclude production decoder/transition refinement, a composed scheduler, OS process termination, physical memory bounds, evaluator equivalence and liveness/fairness. I found no misleading scope statement or false-PASS path in the inspected verifier flow and no constructed input/event trace violating a model invariant.
