# TB01 independent review B (tier 3)

Verdict: **no constructed breach** of the frozen model claims. This is an advisory adversarial review, not proof authority or production acceptance. The reviewed manifest is `formal/traffic/block.json`, SHA256 `7683d900cb639ee71051144edb1bb39e9c3918cb5a6cb77a421dc2839daed318`.

I read all four prior Luna/Sol JSON records and their Markdown notes before reaching this verdict. I independently inspected the Resources, Reuse and Ingress model interfaces, reachability definitions, invariant proofs and witnesses; the theorem/claim/witness inventories; the registered Audit metaprogram; the traffic verifier and its shared inventory, source restriction, review, isolation and hashing helpers; and the README and implementation handoff. The mechanical-closure-verification skill's distinction between advisory review and registered evidence applies here. I made no production, model or verifier changes.

## Independent execution

In owned `build/traffic-proof-review/TB01/astra-b/` scratch I copied and freshly compiled each of the three frozen modules, then executed the unchanged registered auditor. Every Lean invocation used `scripts/lean_offline.py` with `--trust=0 -DwarningAsError=true -DgenInjectivity=false -j1`. The audit returned exactly the 560 registered theorem/type records with empty axiom lists; all three fresh olean hashes matched candidate build A. This is one additional review build, not a replacement for the gate's required two builds. `checks.json`, the three module logs and `audit.jsonl` preserve the results.

`Probe.lean` and its successful `probe.log` supply executable boundary checks. Starting from the model's initial admissions, joining A and B, dispatching, cancelling both, then completing preserves the running owner until completion, releases both job lists, creates no subscribers, and caches the independent evaluator value. Repeating that completion is a no-op. A cache hit at the subscriber cap is refused. The process trace reserve/launch/start/stop/late-completion/new-reservation/wrong-reap retains the stopping incarnation and its only slot. Equality with the absolute deadline rejects a read and a valid-shaped frame; a payload/announced-length disagreement rejects the frame; exhausted zero-rate bucket credits do not increase admitted count; a third retry is rejected. These outcomes agree with the registered claims, rather than furnishing a breach.

I also exercised the actual Python inventory checker against the candidate audit stream. Removing a theorem, duplicating a theorem, injecting `sorryAx` into an axiom list, and changing a theorem type each produced rejection. Current frozen input hashes and claim/witness ownership checks succeeded. These finite checks do not prove the Python verifier correct.

## Adversarial assessment

Resources guards every declared ledger bound and simultaneous owner uniqueness. Stop does not release a process reservation, full tickets control completion, and only the matching stopping worker can disappear on the modeled reap event. Externally reused generic ledger owners still permit stale release; W19 explicitly demonstrates and excludes that hazard. `processCharges` uses zero-byte charges. Finite warm replay proves unchanged launch counts for explicit successful start/completion events, without implying real execution success, JVM equivalence or measured memory bounds.

Reuse's structural keys preserve the full modeled context, kind and options. Behavior sharing intentionally ignores the selected structural metric. Cancellation and supersession remove scoped subscribers while keeping running owners; queued orphans are pruned. Completion and cache/pin soundness are relative to the independent mathematical `eval`. The retained subscriber and cache capacities count records rather than physical bytes. Full delivery comparison prevents a mismatched current envelope from being published. Real capability issuance, asynchronous capture, evaluator purity, lock atomicity and the linkage between Reuse completions and process/frame tickets still require the documented production/composition bridges. A stale external callback is not made safe merely by naming its key in Reuse.

Ingress treats clocks and credits as exact natural numbers, rejects backwards bucket ticks, and separates public/control credit and handler ownership. Request and frame inputs are already parsed values, with boolean schema assertions and checked allocation plans; these are not raw decoders or actual allocations. Retry reachability bounds attempts and preserves identity/deadline/kind; it does not connect existential bucket inputs into a single execution history. Its separate rate theorem requires a reachable bucket. Environment filtering proves allowed names, not harmless values. None of these limitations is silently promoted to production or composed-system correctness by the current claims or handoff.

The verifier checks frozen byte hashes before snapshotting and consumption, audits theorem names/types and transitive axioms, compares clean build artifacts, and performs placeholder/custom-axiom controls. The source scanner is a restricted-language check, not a sandbox for hostile arbitrary Lean metaprograms; the registered auditor and host remain explicit trust. Review JSON and notes are hash-linked workflow evidence, not an authentication mechanism or mathematical witness. I found no constructed false-PASS execution within the frozen source and declared TCB.

The supplied candidate report remains **BLOCKED** solely for `CANDIDATE_ONLY_REVIEWS_NOT_CHECKED`; it records `modelStatus: VERIFIED`, two agreeing builds, negative controls and verifier tests. The review does not change that report. All 23 production TRF obligations remain OPEN. Any eventual `VERIFIED` result is limited to the three finite registered model claims under Lean, verifier, Python/host and hash trust, with production refinement, composed scheduling, physical resource enforcement, OS termination, fairness and liveness excluded.
