# TB01 independent adversarial review A (tier 3)

**Verdict: no constructed breach of the frozen mathematical claims.** I reviewed manifest SHA256 `7683d900cb639ee71051144edb1bb39e9c3918cb5a6cb77a421dc2839daed318`, all three `Traffic` modules, the theorem/claim/witness maps, `Audit.lean`, the traffic verifier and its relevant shared inventory, source, review, namespace and toolchain helpers, the verifier tests, README and implementation handoff. Before this review I read all four Luna/Sol JSON records and Markdown coverage notes. Their exact JSON byte hashes are recorded in the companion review JSON.

This is an advisory review, not a mathematical discharge or production acceptance. I independently compiled fresh copies of all three modules in `build/traffic-proof-review/TB01/astra-a/`, then ran the registered auditor against those fresh objects. The audit matched all 560 registered declarations and exact type hashes, with empty axiom lists. All Lean invocations used `scripts/lean_offline.py`, `--trust=0 -DwarningAsError=true -DgenInjectivity=false -j1`; no network/toolchain fetching or proof/production changes were used. This extra scratch build does not replace the final normal two-build/review gate.

The supplied candidate report records two agreeing builds, successful negative controls and verifier tests, `modelStatus: VERIFIED`, and overall `BLOCKED` solely because candidate mode deliberately omitted reviews. I verified current frozen input hashes, the complete claim ownership map, and all 22 witness groups against the 560-declaration inventory. Independent mutations of the candidate audit stream—deleting a declaration, duplicating one, adding an axiom dependency, and changing a theorem type—were each rejected by the inventory checker. These results are in `metadata-check.json` in my scratch directory. The gate's private input snapshot, exact input hashes, rechecks, raw audit, toolchain inventory, and declared host/verifier trust address the inspected acceptance path. I found no concrete false-PASS input trace against the current frozen block. Review model labels and independence remain orchestration trust, not kernel facts.

Resources' ledger checks global and every lane's count/declared-byte bounds on insertion, and release removes only the supplied owner. Its uniqueness is simultaneous ownership; immediate release idempotence does not make reused external IDs safe. The explicit `owner_reuse_breach` remains correctly outside the stronger stale-callback interpretation. Pool reservations issue monotonically increasing incarnations; worker start advances serials, completion compares the whole current ticket, stop retains a reservation, and only a matching stopping record can be reaped. `processCharges` has zero byte fields, so process-pool byte bounds do not establish memory accounting. Warm replay is a finite sequence containing successful completions, with no claim about evaluator reset or progress. The registered reachable prewarm and replay witnesses make that use nonempty.

Reuse's invariants cover atomic model transitions with exact structural keys and one independently supplied `eval`. I challenged cancellation followed by completion and readmission: detached running work may finish and populate cache, and a new subscriber receives `eval key` under its own delivery. This behavior satisfies the scoped claims; it is not a cancellation breach. The global subscriber bound also applies to hits and joined work. Job uniqueness, running ownership, queued-orphan removal, cache/pin soundness, delivery binding and latest-channel identity follow the actual guards and inductive transitions. Exact delivery equality is not capability authenticity, actual asynchronous capture, or a complete authorization context. `complete` supplies `eval key` directly; it cannot certify Java output or stale real callbacks. Those implementation/composition bridges remain explicitly OPEN.

Ingress proves conservation for successful logical charges with natural-number time, not all network attempts or physical clock behavior. Separate public/control buckets and handler owner lists retain their declared envelopes. Header/body/frame values are already parsed, with explicit validity fields; payload/decoded-message semantic correspondence is not supplied by those flags. The checked allocation result is a size plan, not an allocation. Successful frames consume the busy phase, while malformed, late and duplicate frames retire it. Retry guards bound successful retries to two and require identity, kind, pre-dispatch capacity rejection, deadline, clock agreement and credit. `RetryReachable` does not thread one bucket history; the rate theorem separately requires a reachable bucket. This is correctly a policy fragment, not proof of composed retry scheduling. Environment filtering concerns names only, not whether an allowed value contains a secret.

I added independent scratch-only Lean examples in `Replay.lean` and checked them with exit code 0. Their explicit inputs and expected/actual equalities cover: a ledger of count-cap 2 and byte-cap 3 accepting a two-byte charge and rejecting a second two-byte charge; a prewarmed worker completing context 41, starting 42, then ignoring the old context-41 ticket; both subscribers detaching from a running shared job before completion and a cache-hit readmission; queued orphan removal before attempted dispatch; two chained retry successes followed by third-attempt rejection despite one token remaining; and a valid frame accepted before its deadline, rejected on idle replay, and rejected exactly at expiration. These are nonvacuity/adversarial checks, not alleged breaches, and their source and empty compiler log are retained in owned scratch.

The current claim statements and handoff distinguish three independent mathematical fragments from a composed scheduler, actual parser/clock/process semantics, measured bytes, Java equivalence, credential isolation and liveness. Miniature policy counterexamples are explicitly not production exploits. All 23 TRF production obligations remain OPEN. None of the boundary challenges above constructs an initial state/input/event trace contradicting a registered theorem or the published model-only scope. The final normal gate and its kernel evidence remain authoritative.
