# SQL01 tier 2 adversarial review — Sol A

Verdict: `no_constructed_breach` for frozen SQL01 block SHA-256 `e8cdff342aeba6687f88e3e52faa32c98a8a8b5acfdf435f28baa3eac6ddb2e6`. I read both fresh Luna review records and notes. Their exact JSON SHA-256 values are bound in the companion record. All 40 manifest input hashes matched current bytes; no frozen input was changed.

I inspected the `syntax()` change and its uses for adapter-body and default comparisons, schema-loop recognition, and trusted integrity-function pins. Parsed AST nodes encode their class and fields; lists remain arrays. Strings now encode as tagged sequences of Python Unicode code points, so one astral scalar and an explicit high/low surrogate pair remain distinct. The tag cannot collide with an accepted list or AST node, and arbitrary dictionaries reject. Booleans and integers retain distinct JSON values, bytes use a separate tag, and unsupported field values reject. Only an empty `type_params` AST field is normalized away; nonempty generic parameters reject. I found no accepted AST identity collision that changes the frozen adapter or integrity routine semantics.

My independent offline checks matched the manifest digest and all 40 registered input hashes. I recomputed the three `_registry`, `_read_artifact`, and `_strict_json` AST fingerprints; each matched `formal/sql/bridge-policy.json`. A direct astral/surrogate-pair probe produced unequal Python strings and unequal encoded AST identities. Nine edge-case strings round-tripped through their code-point arrays. All five focused AST identity tests passed on Python 3.10 and 3.12. Fresh restricted extraction returned 10 queries and 31 mappings, matched every frozen source hash, and had canonical SHA-256 `dae5f57602c1e0600214f820938c4e7c1c7237c20c23dbb1895d45a5c721f371`.

The supplied candidate report at `build/sql-separation/sql-20260929T044407Z-da58461e/report.json` records `blockStatus: VERIFIED`, 83 declarations, no project axioms, two clean offline deterministic builds, and the same correspondence hash. I inspected its summary but did not independently rerun Lean. Its overall `status: BLOCKED` awaits the renewed review gate. The parent's 59 focused Python 3.12 tests and 37 Python 3.10 bridge tests are supplied evidence, separate from my five-test runs under each interpreter.

The Lean result proves separation in the generated finite model. Production correspondence is checked by the restricted extractor, whose integrity routines and source interpretation remain trusted. The proof does not establish full Python, JavaScript, JSON, or SQLite semantic refinement, universal immunity, future revisions, or whole-trace input independence. The original 24 general portal obligations remain `OPEN`. No concrete accepted input or execution violating the frozen SQL statement/value separation invariant was constructed. This review is advisory and does not itself grant proof or release closure.
