#!/usr/bin/env python3
"""Materialize and check portable finite policy kernels exported from Lean.

Generation is not proof: verification additionally kernel-checks every exported
Boolean valuation and executes the actual JS/Java policy kernels exhaustively.
The finite Boolean boundary deliberately excludes wire decoding and host loops.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path
import shutil
import subprocess
import sys

from lean_offline import ROOT, clean_environment, installed_toolchain, isolated_command

BEGIN = '// BEGIN LEAN POLICY KERNEL\n'
END = '// END LEAN POLICY KERNEL\n'
SCHEMA = {
    'feedbackSuccess': (10, 'AlloyStudio.SessionBridge.feedbackSuccess'),
    'guidanceSuccess': (13, 'AlloyStudio.SessionBridge.guidanceSuccess'),
    'poolChoose': (2, 'AlloyStudio.PoolBridge.choosePolicy'),
    'poolFinish': (2, 'AlloyStudio.PoolBridge.finishPolicy'),
}


def validate(data):
    if not isinstance(data, dict) or set(data) != set(SCHEMA):
        raise ValueError('The exported policy inventory differs from the registered schema')
    for name, (arity, _) in SCHEMA.items():
        row = data[name]
        if (not isinstance(row, dict) or set(row) != {'arity', 'acceptedMasks'}
                or type(row['arity']) is not int or row['arity'] != arity
                or not isinstance(row['acceptedMasks'], list)
                or any(type(mask) is not int or not 0 <= mask < 2 ** arity for mask in row['acceptedMasks'])
                or row['acceptedMasks'] != sorted(set(row['acceptedMasks']))):
            raise ValueError(f'Invalid finite policy: {name}')
    return data


def render_js(data):
    tables = json.dumps(data, sort_keys=True, separators=(',', ':'))
    return BEGIN + f'const LEAN_POLICIES = {tables};\n' + '''function verifiedPolicy(name, atoms) {
  if (!Object.hasOwn(LEAN_POLICIES, name)) return false;
  const policy = LEAN_POLICIES[name];
  if (!Array.isArray(atoms) || atoms.length !== policy.arity) return false;
  let mask = 0;
  for (let index = 0; index < atoms.length; index += 1) {
    if (typeof atoms[index] !== 'boolean') return false;
    if (atoms[index]) mask |= (1 << index);
  }
  return policy.acceptedMasks.includes(mask);
}
''' + END


def render_java(data):
    choose = ', '.join(str(i in data['poolChoose']['acceptedMasks']).lower() for i in range(4))
    finish = ', '.join(str(i in data['poolFinish']['acceptedMasks']).lower() for i in range(4))
    return f'''package live;

/** Generated by scripts/bridge_policies.py from kernel-checked Lean policies. */
public final class BridgePolicies {{
    private static final boolean[] CHOOSE = {{ {choose} }};
    private static final boolean[] FINISH = {{ {finish} }};
    private BridgePolicies() {{ }}
    public static boolean choose(boolean hasBest, boolean improves) {{
        return CHOOSE[(hasBest ? 1 : 0) | (improves ? 2 : 0)];
    }}
    public static boolean finish(boolean nonempty, boolean complete) {{
        return FINISH[(nonempty ? 1 : 0) | (complete ? 2 : 0)];
    }}
}}
'''


def js_region(source):
    if source.count(BEGIN) != 1 or source.count(END) != 1:
        raise ValueError('Expected one generated JavaScript policy kernel')
    start, end = source.index(BEGIN), source.index(END) + len(END)
    if start >= end:
        raise ValueError('Reversed policy markers')
    return source[start:end]


def check_generated(root, data):
    if js_region((root / 'web/app.js').read_text()) != render_js(data):
        raise ValueError('Browser policy kernel differs from its Lean export')
    if (root / 'engine/src/live/BridgePolicies.java').read_text() != render_java(data):
        raise ValueError('Java policy kernel differs from its Lean export')
    if json.loads((root / 'formal/bridges/policies.json').read_text()) != data:
        raise ValueError('Saved policy values differ from Lean evaluation')


def certificate_source(data):
    lines = ['import AlloyStudio.SessionBridge', 'import AlloyStudio.PoolBridge',
             'namespace AlloyStudio.BridgeCases']
    for name, (arity, function) in SCHEMA.items():
        accepted = set(data[name]['acceptedMasks'])
        for mask in range(2 ** arity):
            atoms = ', '.join('true' if mask & (1 << bit) else 'false' for bit in range(arity))
            answer = str(mask in accepted).lower()
            lines.append(f'theorem {name}_{mask} : {function} [{atoms}] = {answer} := by decide')
    lines.append('end AlloyStudio.BridgeCases')
    return '\n'.join(lines) + '\n'


def export(root, cwd, objects, toolchain, run):
    shutil.copyfile(root / 'formal/ExportBridges.lean', cwd / 'ExportBridges.lean')
    data = run([str(toolchain / 'bin/lean'), '--trust=0', '-DwarningAsError=true',
                '-DgenInjectivity=false', '-j1', '--run', 'ExportBridges.lean'],
               cwd, clean_environment(toolchain, objects), cwd / 'export.log')
    return validate(json.loads(data))


def verify_build(root, work, objects, toolchain, run):
    """Called separately in each clean formal build, after model compilation."""
    work.mkdir()
    environment = clean_environment(toolchain, objects)
    lean = str(toolchain / 'bin/lean')
    flags = ['--trust=0', '-DwarningAsError=true', '-DgenInjectivity=false', '-j1']
    data = export(root, work, objects, toolchain, run)
    check_generated(root, data)
    (work / 'AlloyStudioBridgeRows.lean').write_text(certificate_source(data))
    run([lean, *flags, '-o', str(objects / 'AlloyStudioBridgeRows.olean'), 'AlloyStudioBridgeRows.lean'],
        work, environment, work / 'kernel-rows.log')
    audit = (root / 'formal/Audit.lean').read_text().replace('import AlloyStudio\n',
                                                         'import AlloyStudioBridgeRows\n')
    (work / 'AuditRows.lean').write_text(audit)
    audit_data = run([lean, *flags, 'AuditRows.lean'], work, environment, work / 'kernel-row-inventory.jsonl')
    rows = [json.loads(line) for line in audit_data.decode().splitlines()]
    if any(row.get('kind') != 'theorem' or row.get('axioms') != [] for row in rows):
        raise ValueError('A generated row proof has an axiom dependency')
    expected = {f'AlloyStudio.BridgeCases.{name}_{mask}' for name, (arity, _) in SCHEMA.items()
                for mask in range(2 ** arity)}
    actual = {row['name'] for row in rows if row['module'] == 'AlloyStudioBridgeRows'}
    if actual != expected:
        raise ValueError('Generated row proof coverage differs from the complete finite domain')
    # Source is the actual inline kernel used by the portal, not a second JS model.
    js = js_region((root / 'web/app.js').read_text())
    probe = js + '''
const outputs = {};
for (const [name, policy] of Object.entries(LEAN_POLICIES)) {
  let values = '';
  for (let mask = 0; mask < 2 ** policy.arity; mask += 1) {
    const atoms = Array.from({ length: policy.arity }, (_, i) => Boolean(mask & (1 << i)));
    values += verifiedPolicy(name, atoms) ? '1' : '0';
  }
  for (const bad of [null, {}, [], [true], Array(policy.arity), Array(policy.arity).fill(1),
                     Array(policy.arity + 1).fill(true), Array(policy.arity).fill(null)]) {
    if (verifiedPolicy(name, bad)) throw new Error('Malformed policy input accepted');
  }
  outputs[name] = values;
}
if (verifiedPolicy('unknown', []) || verifiedPolicy('__proto__', [])) throw new Error('Unknown policy accepted');
console.log(JSON.stringify(outputs));
'''
    (work / 'policies.mjs').write_text(probe)
    node = shutil.which('node')
    javac, java = shutil.which('javac'), shutil.which('java')
    if not all((node, javac, java)):
        raise RuntimeError('Node, Java and javac are required for implementation bridge checking')
    actual_js = json.loads(run([node, 'policies.mjs'], work, environment, work / 'javascript.log'))
    expected_js = {name: ''.join('1' if mask in row['acceptedMasks'] else '0' for mask in range(2 ** row['arity']))
                   for name, row in data.items()}
    if actual_js != expected_js:
        raise ValueError('Actual JavaScript kernel disagrees with the proved policy')
    shutil.copyfile(root / 'engine/src/live/BridgePolicies.java', work / 'BridgePolicies.java')
    (work / 'PolicyProbe.java').write_text('''package live;
public final class PolicyProbe {
 public static void main(String[] args) {
  StringBuilder result = new StringBuilder();
  for (int mask = 0; mask < 4; mask++) result.append(BridgePolicies.choose((mask & 1) != 0, (mask & 2) != 0) ? '1' : '0');
  result.append(' ');
  for (int mask = 0; mask < 4; mask++) result.append(BridgePolicies.finish((mask & 1) != 0, (mask & 2) != 0) ? '1' : '0');
  System.out.println(result);
 }
}
''')
    classes = work / 'java-classes'
    classes.mkdir()
    run([javac, '-encoding', 'UTF-8', '-d', str(classes), 'BridgePolicies.java', 'PolicyProbe.java'],
        work, environment, work / 'javac.log')
    actual_java = run([java, '-cp', str(classes), 'live.PolicyProbe'], work, environment, work / 'java.log').decode().strip()
    if actual_java != expected_js['poolChoose'] + ' ' + expected_js['poolFinish']:
        raise ValueError('Actual Java kernel disagrees with the proved policy')
    # An actual false row must fail kernel checking, even if native export or a
    # generator is corrupted. This is a counterexample to choosing the later tie.
    (work / 'BadRow.lean').write_text('import AlloyStudio.PoolBridge\n'
        'theorem corrupt_tie : AlloyStudio.PoolBridge.choosePolicy [true, false] = true := by decide\n')
    try:
        run([lean, *flags, 'BadRow.lean'], work, environment, work / 'bad-row.log')
    except ValueError:
        if 'decide' not in (work / 'bad-row.log').read_text():
            raise ValueError('The bad-row control failed for an unrelated reason')
    else:
        raise ValueError('The false tie row passed kernel checking')
    return {'status': 'VERIFIED', 'kernelCheckedRows': len(expected), 'javascriptValuations': sum(map(len, actual_js.values())),
            'javaValuations': 8, 'malformedInputs': 'REJECTED', 'falseTieRow': 'REJECTED',
            'policies': data,
            'scope': 'Complete typed Boolean domains of the generated policy kernels',
            'excluded': ['Wire/field extraction', 'Java iteration and cost arithmetic',
                         'JavaScript async bookkeeping', 'Distance computation and source mapping']}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--lean-path', type=Path, required=True)
    parser.add_argument('--generate', action='store_true')
    parser.add_argument('--output', type=Path, required=True)
    args = parser.parse_args()
    _, toolchain = installed_toolchain()
    args.output.mkdir(parents=True, exist_ok=False)
    def run(command, cwd, environment, log):
        result = subprocess.run(isolated_command(command), cwd=cwd, env=environment,
                                stdout=subprocess.PIPE, stderr=subprocess.STDOUT, timeout=180)
        log.write_bytes(result.stdout)
        if result.returncode:
            raise ValueError(f'Bridge command failed; see {log}')
        return result.stdout
    data = export(ROOT, args.output.resolve(), args.lean_path.resolve(), toolchain, run)
    if args.generate:
        app = ROOT / 'web/app.js'
        source = app.read_text()
        source = source.replace(js_region(source), render_js(data)) if BEGIN in source else render_js(data) + '\n' + source
        app.write_text(source)
        (ROOT / 'engine/src/live/BridgePolicies.java').write_text(render_java(data))
        (ROOT / 'formal/bridges').mkdir(exist_ok=True)
        (ROOT / 'formal/bridges/policies.json').write_text(json.dumps(data, indent=2) + '\n')
    check_generated(ROOT, data)
    print('Portable policy kernels match Lean export; run verify_lean.py for kernel certificates and runtime checks.')


if __name__ == '__main__':
    main()
