"""Render frozen specification and independently extracted service data for Lean."""
import json
from pathlib import Path
from service_initial_bridge import extract


def string(value):
    return json.dumps(value,ensure_ascii=False)


def value_string(value):
    return value if isinstance(value,str) else json.dumps(value,separators=(',',':'),allow_nan=False)


def graph_term(graph):
    return '[\n'+',\n'.join('  ⟨'+', '.join(string(v) for v in (path,kind,value_string(value)))+'⟩'
                            for path,kind,value in graph)+'\n]'


def quantities_term(limits):
    rows=[]
    for row in limits:
        value=row['value']; n,d=value.as_integer_ratio() if type(value) is float else (value,1)
        if type(n) is not int or n<0 or d<=0:raise ValueError('Invalid profile rational')
        rows.append('  ⟨'+string(row['id'])+', '+str(n)+', '+str(d)+', '+
                    ('true' if 'nonnegative' in row['encoding'] else 'false')+'⟩')
    return '[\n'+',\n'.join(rows)+'\n]'


def spec_source(profile,graph):
    out=['import ServiceProfile.Model\n\nnamespace AlloyStudio.ServiceProfile.Frozen\nopen Model\n']
    out.append('def profile : List Quantity := '+quantities_term(profile['limits']))
    out.append('def graph : List Cell := '+graph_term(graph))
    fields=profile['initialExpectations']
    for name,key in (('zeroCounters','zeroIntegers'),('emptyContainers','emptyContainers'),
                     ('falseBooleans','falseBooleans'),('noneValues','noneValues')):
        out.append('def '+name+' : List String := ['+', '.join(string(v) for v in fields[key])+']')
    for name in ('scalarValues','referenceTargets','externalBindings'):
        out.append('def '+name+' : List (String × String) := ['+', '.join(
            '⟨'+string(k)+', '+string(value_string(v))+'⟩' for k,v in fields[name].items())+']')
    out.append('def referenceEqualities : List (String × String) := ['+', '.join(
        '⟨'+string(a)+', '+string(b)+'⟩' for a,b in fields['referenceEqualities'])+']')
    out.append('end AlloyStudio.ServiceProfile.Frozen\n')
    return '\n\n'.join(out)


def extracted_source(profile,graph):
    return '''import ServiceProfile.Model
import TrafficProfile.Extracted

/- Generated by the closed constructor interpreter and numeric source bindings. -/
namespace AlloyStudio.ServiceProfile.Extracted
open Model

def profile : List Quantity := '''+quantities_term(profile['limits'])+'''

def graph : List Cell := '''+graph_term(graph)+'''

def initial (input : Inputs) : State := {
  inputs := input
  profile := profile
  graph := graph
  http := HttpProfile.Extracted.initial HttpProfile.Extracted.defaults false input.clock
}

end AlloyStudio.ServiceProfile.Extracted
'''


def extracted_profile(root,profile):
    from service_numeric_bindings import extracted_values
    values=extracted_values(root,profile)
    return dict(profile,limits=[dict(row,value=values[row['id']]) for row in profile['limits']])


def generate(root):
    root=Path(root)
    profile=json.loads((root/'closure/traffic-refinement/service-profile.json').read_text())
    graph=extract(root)['graph']
    fixture=json.loads((root/'closure/traffic-refinement/initial-graph.json').read_text())['graph']
    return {'Frozen.lean':spec_source(profile,fixture),
            'Extracted.lean':extracted_source(extracted_profile(root,profile),graph)}


if __name__=='__main__':
    root=Path(__file__).resolve().parents[1]
    for name,source in generate(root).items():
        (root/'formal/service_profile/ServiceProfile'/name).write_text(source)
