import AdmissionModel
namespace AlloyStudio.IngressAdmission.Extracted
-- Generated by scripts/admission_bridge.py from admitted production AST.
def reserve (limit owner : Nat) (creditAllowed : Bool) (state : State) : Result :=
  IngressAdmission.reserve .ge 1 limit owner creditAllowed state

def release (owner : Nat) (state : State) : State :=
  IngressAdmission.release 1 owner state

def publicHandlers : Nat := 30
def controlHandlers : Nat := 2
def publicBurst : Nat := 60
def controlBurst : Nat := 4
def publicRate : Nat := 30
def controlRate : Nat := 2
def controlPortDefault : Nat := 0
def laneLimit (control : Bool) : Nat := if control then controlHandlers else publicHandlers
def allocation : List LifeAction := [.reserve, .allocate, .register, .attempt, .identify, .start]
def refusal : List LifeAction := [.refuse, .close]
def preAttemptFailure : List LifeAction := [.reserve, .allocate, .unregister, .release]
def constructorFailure : List LifeAction := [.reserve, .unregister, .release]
def reaping : List LifeAction := [.markObservation, .joinReturned, .terminate, .clearObservation, .unregister, .release]
def retainedOnAmbiguousStart : List LifeAction := [.reserve, .allocate, .register, .attempt, .identify, .start]
def retainedOnUnstartedJoin : List LifeAction := [.reserve, .allocate, .register, .attempt, .identify, .markObservation, .joinRefused]
def retainedOnLiveJoin : List LifeAction := [.reserve, .allocate, .register, .attempt, .identify, .start, .markObservation, .joinReturned, .clearObservation]
def canReap (phase : Phase) : Bool := reclaimable .joined phase
def stickyObservationFailure : Bool := true
def failObservation (entry : ThreadEntry) : ThreadEntry := failEntry stickyObservationFailure entry
def tokenUnit : Nat := 1000000000
def refillCredit (capacity credit elapsed rate : Nat) : Nat := (clip capacity (credit + (elapsed * rate)))
def chargeCredit (credit : Nat) : Nat := credit - tokenUnit
def availableCredit (credit : Nat) : Bool := compare .ge credit tokenUnit
end AlloyStudio.IngressAdmission.Extracted
