package live;

/** Generated by scripts/bridge_policies.py from kernel-checked Lean policies. */
public final class BridgePolicies {
    private static final boolean[] CHOOSE = { true, false, true, true };
    private static final boolean[] FINISH = { false, false, false, true };
    private BridgePolicies() { }
    public static boolean choose(boolean hasBest, boolean improves) {
        return CHOOSE[(hasBest ? 1 : 0) | (improves ? 2 : 0)];
    }
    public static boolean finish(boolean nonempty, boolean complete) {
        return FINISH[(nonempty ? 1 : 0) | (complete ? 2 : 0)];
    }
}
